/**
 * Migration utilities
 *
 * Migrations are generated by drizzle-kit and stored in ./sql/
 * Run migrations with: pnpm db:migrate
 */

export { migrate } from 'drizzle-orm/postgres-js/migrator'

/**
 * Migration configuration
 */
export const migrationConfig = {
  migrationsFolder: './packages/database/src/migrations/sql',
}
